apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-processor-worker-deployment
  labels:
    app: video-processor
spec:
  selector:
    matchLabels: 
      app: video-processor-worker
  template:
    metadata:
      labels:
        app: video-processor-worker
    spec:
      containers:
        - name: c-video-processor-worker
          image: "#{APP_IMAGE}#"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 25
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 60
            failureThreshold: 3
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ConsumerOptions__QueueName
              value: videos-to-process
            - name: ConsumerOptions__ConcurrentMessageLimit
              value: '3'
            - name: S3BucketOptions__VideosBucket
              value: "#{VIDEOS_BUCKET_NAME}#"
            - name: S3BucketOptions__ZipFilesBucket
              value: "#{ZIPFILES_BUCKET_NAME}#"
            - name: VideoManagerClientOptions__Host
              value: "#{MEDIA_MANAGER_HOST}#"
            - name: SMTPSenderOptions__Host
              value: "#{SMTP_HOST}#"
            - name: SMTPSenderOptions__Port
              value: "#{SMTP_PORT}#"
            - name: SMTPSenderOptions__User
              value: "#{SMTP_USER}#"
            - name: SMTPSenderOptions__FromEmail
              value: "#{SMTP_FROM_EMAIL}#"
            - name: SMTPSenderOptions__Password
              valueFrom:
                secretKeyRef: 
                  name: video-processor-worker-secrets
                  key: smtp-password
            - name: VideoManagerClientOptions__ApiKey
              valueFrom:
                secretKeyRef: 
                  name: video-processor-worker-secrets
                  key: media-manager-api-key
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef: 
                  name: video-processor-worker-secrets
                  key: aws-access-key-id 
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef: 
                  name: video-processor-worker-secrets
                  key: aws-secret-access-key 
            - name: AWS_SESSION_TOKEN
              valueFrom:
                secretKeyRef: 
                  name: video-processor-worker-secrets
                  key: aws-session-token 
