name: CD
on:
  push:
    branches: 
      - main
    tags:
      - v*

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  AWS_REGION: us-east-1
  AWS_CLUSTER_NAME: ${{ secrets.AWS_CLUSTER_NAME }}

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PUBLISH_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          atcorrea/video-processor-worker
        tags: |
          type=sha

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}

    - uses: cschleiden/replace-tokens@v1
      name: Replace tokens in kubernetes files
      with:
        files: '[".kubernetes/*.yaml"]'
      env:
        APP_IMAGE: ${{ steps.meta.outputs.tags }}
        VIDEOS_BUCKET_NAME: ${{ vars.VIDEOS_BUCKET_NAME }}
        ZIPFILES_BUCKET_NAME: ${{ vars.ZIPFILES_BUCKET_NAME }}
        SQS_VIDEOS_TO_PROCESS_QUEUE: ${{ vars.SQS_VIDEOS_TO_PROCESS_QUEUE }}
        AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ env.AWS_SESSION_TOKEN }}
        SMTP_HOST: ${{ vars.SMTP_HOST }}
        SMTP_PORT: ${{ vars.SMTP_PORT }}
        SMTP_USER: ${{ vars.SMTP_USER }}
        SMTP_FROM_EMAIL: ${{ vars.SMTP_FROM_EMAIL }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        MEDIA_MANAGER_HOST: ${{ vars.MEDIA_MANAGER_HOST }}
        
    - name: AWS Cli login
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Update kubeconfig for EKS
      run: |
        aws eks update-kubeconfig --name ${{ env.AWS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f ./.kubernetes/secrets.yaml
        kubectl apply -f ./.kubernetes/deployment.yaml
        kubectl apply -f ./.kubernetes/service.yaml
        kubectl apply -f ./.kubernetes/hpa.yaml
